import random

_items = [
    "Astuccio", "Zaino", "Incudine", "Gatto di porcellana", "Mappa del tesoro", 
    "Cuscinetto a sfere", "Telescopio", "Sveglia", "Piumino da cipria", "Binocolo",
    "Satellite Sputnik", "Telescopio James Webb", "Sonda Voyager 1", "Stazione Spaziale Internazionale", "Rover Marziano",
    "Rovazzi", "Mina", "Guglielmo Hotel", "Ruggero", "Devin", "Ligabue", "Jovanotti", "Raurora", "Bandit", "Giovannini",
    "Semaforo", "Boa da ormeggio", "Incubatrice", "Microfono", "Sveglia a vapore",
    "Mongolfiera", "Dirigibile", "Aliante", "Fregata", "Rompi-ghiaccio",
    "Centrale Idroelettrica", "Diga di Hoover", "Ponte di Brooklyn", "Turbina Eolica", "Reattore a Fusione",
    "Macchina da scrivere", "Grammofono", "Telegrafo", "Bussola", "Sestante",
    "Mulinello da pesca", "Arpione", "Ancora", "Timone", "Paracadute",
    "Drone", "Microchip", "Fibra ottica", "Laser", "Pannello solare",
    "Batteria al litio", "Trasformatore", "Dinamo", "Bobina di Tesla", "Magnetron",
    "Cactus", "Bonsai", "Orchidea", "Mangrovia", "Eucalipto", 
    "Margherita", "Girasole", "Tulipano", "Lavanda", "Papiro",
    "Martello", "Cacciavite", "Pinza", "Chiave inglese", "Smerigliatrice",
    "Bullone", "Vite", "Chiodo", "Rivetto", "Saldatrice",
    "Pianoforte", "Violino", "Chitarra", "Batteria", "Sassofono",
    "Tromba", "Arpa", "Oboe", "Flauto", "Fisarmonica",
    "Spazzolino da denti", "Telecomando", "Calzino spaiato", "Tostapane", "Graffetta", "Ombrello", "Borraccia",
    "Cuscino", "Divano", "Lampadario", "Tappeto", "Specchio",
    "Orologio a cucù", "Quadro", "Statua", "Vaso", "Tenda",
    "Pane", "Formaggio", "Mela", "Pizza", "Sushi",
    "Caffettiera", "Frullatore", "Forno a microonde", "Lavastoviglie", "Frigorifero",
    "Scarpa", "Cappello", "Guanto", "Cravatta", "Sciarpa",
    "Occhiali", "Orologio da polso", "Anello", "Collana", "Braccialetto",
    "Libro", "Giornale", "Rivista", "Fumetto", "Enciclopedia",
    "Matita", "Penna", "Gomma", "Righello", "Compasso",
    "Smartphone", "Tablet", "Monitor", "Tastiera", "Mouse",
    "Cuffie", "Altoparlante", "Webcam", "Scanner", "Stampante",
    "Bicicletta", "Skateboard", "Monopattino", "Pattini", "Tandem",
    "Monolite nero", "Macchina del tempo", "Sottomarino giallo", "Palla di vetro con neve", "Disco in vinile d'oro",
    "Moneta d'oro", "Calzino bucato", "Elton John", "Sicilia", "Matteo Renzi", "Plettro magico", "Telecomando universale", "Zaino invincibile", 
    "Sfera di cristallo appannata", "Beyoncé", "Isola di Pasqua", "Donald Trump", "Cerniera lampo arrugginita", "Gatto di porcellana", "Freddie Mercury", 
    "Groenlandia", "Silvio Berlusconi", "Spazzolino da denti usato", "Dente di drago", "Lady Gaga", "Madagascar", "Angela Merkel", "Ombrello rotto", 
    "Cuffie bluetooth", "Vasco Rossi", "Isola d'Elba", "Joe Biden", "Libro senza pagine", "Teschio di plastica", "Rihanna", "Isola che non c'è", 
    "Emmanuel Macron", "Bussola rotta", "Sasso a forma di cuore", "Jovanotti", "Sardegna", "Giorgia Meloni", "Piuma di fenice", "Sveglia a molla", 
    "David Bowie", "Ibiza", "Barack Obama", "Mela morsicata", "Tappo di bottiglia", "Laura Pausini", "Isola di Wight", "Vladimir Putin", "Chiave inglese", 
    "Soldatino di piombo", "Mick Jagger", "Capri", "Kim Jong-un", "Vaso cinese", "Accendino scarico", "Fedez", "Isola di Giava", "Justin Bieber", 
    "Statua di sale", "Occhiali da sole", "Ligabue", "Isola di Man", "Sergio Mattarella", "Palla di cannone", "Guanto sinistro", "Tiziano Ferro", 
    "Corsica", "Boris Johnson", "Fischietto di legno", "Anello di fidanzamento", "Madonna", "Zanzibar", "Xi Jinping", "Candela profumata", 
    "Cacciavite a stella", "Andrea Bocelli", "Isola di Rodi", "Giuseppe Conte", "Mappa del tesoro", "Carillon rotto", "Eminem", "Isola di Pasqua", 
    "Mario Draghi", "Boccale di birra", "Dadi truccati", "Gianna Nannini", "Isola di Creta", "Elly Schlein", "Frammento di meteorite", "Pennello da barba", 
    "Bob Dylan", "Isola di Mauritius", "Matteo Salvini", "Pipa di schiuma", "Chitarra scordata", "Shakira", "Isola di Maiorca", "Nicola Kadri", 
    "Lampadina fulminata", "Coltellino svizzero", "Ed Sheeran", "Tenerife", "Luigi Di Maio", "Telescopio portatile", "Maschera antigas", "Adele", 
    "Isola di Formosa", "Viktor Orban", "Dente di squalo", "Biglia di vetro", "Harry Styles", "Santorini", "Ursula von der Leyen", "Francobollo raro", 
    "Corda di canapa", "Ariana Grande", "Isola di Cipro", "Justin Trudeau", "Lanterna a olio", "Pezzo di formaggio", "Billie Eilish", "Isola di Sumatra", 
    "Narendra Modi", "Martello da guerra", "Siringa di platino", "Dua Lipa", "Isola di Bornholm", "Pedro Sanchez", "Cesto di vimini", "Bottiglia di rum", 
    "Katy Perry", "Isola di Skye", "Rishi Sunak", "Lente d'ingrandimento", "Medaglia al valore", "Taylor Swift", 
    "Isola di Mykonos", "King Charles III", "Pergamena antica", "Orologio da taschino", "Bruce Springsteen", 
    "Isola di Moorea", "Volodymyr Zelensky", "Cranio di corvo", "Osso di dinosauro", "Drake", "Isola di Boracay", 
    "Pope Francis", "Secchio di vernice", "Pennarello indelebile", "Miley Cyrus", "Isola di Lampedusa", "Kamala Harris", 
    "Bastone da passeggio", "Fiala di veleno", "The Weeknd", "Isola di Malta", 
    "Benjamin Netanyahu", "Corno di bue", "Cravatta di seta", "Bruno Mars", "Isola di Murano", 
    "Sanna Marin", "Ferro di cavallo", "Punta di freccia", "Post Malone", "Isola di Burano", "Jair Bolsonaro", 
    "Serratura arrugginita", "Fazzoletto ricamato", "Coldplay", "Isola di Koh Samui", 
    "Alexander De Croo", "Pietra focaia", "Candela nera", "Imagine Dragons", "Isola di Bora Bora", 
    "Re Felipe VI", "Sfera di neve", "Manette d'acciaio", "Arctic Monkeys", "Isola di Vancouver", 
    "Mark Rutte", "Ventaglio di piume", "Monocolo d'oro", "Maneskin", "Isola di Ponza", 
    "Frank-Walter Steinmeier", "Fischietto d'argento", "Boccetta di profumo", "Zucchero Fornaciari", 
    "Isola di Stromboli", "Cyril Ramaphosa", "Dado a sei facce", "Pelle di lupo", "Eros Ramazzotti", 
    "Isola di Vulcano", "Alvaro Soler", "Lingotto di piombo", "Spilla da balia", "Maluma", "Isola di Panarea",
    "Bashar al-Assad", "Sogno in barattolo", "Calamita potente", "Rosalía", "Isola di Alicudi", "António Guterres", 
    "Inchiostro invisibile", "Foglia d'oro", "Ozzy Osbourne", "Isola di Filicudi", "Lula da Silva", "Campanello da hotel", 
    "Dente d'oro", "Slash", "Isola di Salina", "Tayyip Erdogan", "Caramella mou", "Smalto rosso", "Travis Scott", "Isola di Ustica", 
    "Kishida Fumio", "Bussola solare", "Microfono d'oro", "Snoop Dogg", "Isola di Palmarola", "Yoon Suk-yeol", "Sabbia del deserto", "Piumino da cipria", 
    "Nicki Minaj", "Isola di Giannutri", "Mohammad bin Salman", "Scheggia di specchio", "Semaforo giocattolo", 
    "Cardi B", "Isola del Giglio", "Re Abdullah II", "Corona di spine", "Chiave di violino", "Enrique Iglesias", 
    "Isola d'Ischia", "Ali Khamenei", "Sigillo di ceralacca", "Cenere di fenice", "Pitbull", "Isola di Procida", "Hassan Sheikh Mohamud", 
    "Morsa da banco", "Chiodo arrugginito", "Gigi D'Alessio", "Isola di Linosa", "Nikos Christodoulides", "Foglietto illustrativo", 
    "Pasticca per la gola", "Orietta Berti", "Isola di Gorgona", "Miguel Díaz-Canel", "Scontrino fiscale", "Biglietto del tram", 
    "Achille Lauro", "Isola di Capraia", "Fumio Kishida", "Guscio di lumaca", "Pezzo di carbone", "Gianni Morandi", "Isola di Pianosa", 
    "Paul Biya", "Tappo di sughero", "Elastico giallo", "Mina", "Isola di Montecristo", "Sheikh Hasina", "Sasso piatto", "Molletta da bucato", 
    "Renato Zero", "Isola di Budelli", "William Ruto", "Scatola di fiammiferi", "Ritratto di ignoto", "Claudio Baglioni", "Isola di Spargi", 
    "Dino Patti Bruni", "Busta per lettere", "Matita spezzata", "Patty Pravo", "Isola di Santa Maria", "Abdel Fattah el-Sisi", "Gessetto bianco", 
    "Sottobicchiere", "Antonello Venditti", "Isola di Razzoli", "Hery Rajaonarimampianina", "Occhio di vetro", "Fischietto d'ottone", ""
    "Francesco De Gregori", "Isola di Santo Stefano", "Nana Akufo-Addo", "Radio a transistor", "Lanterna magica", "Lucio Dalla (ologramma)", 
    "Isola di Tavolara", "Macky Sall", "Calamaro di gomma", "Dado di brodo", "Ivano Fossati", "Isola di Mortorio", 
    "Azali Assoumani", "Coperchio di latta", "Vite a brugola", "Fiorella Mannoia", "Isola di Soffi", "George Weah", 
    "Scatola di latta", "Bullone zincato", "Giorgia", "Isola di Camogli", "Prithvirajsing Roopun", "Filo interdentale",
    "Pila stilo", "Elisa", "Isola di San Pietro", "Bongbong Marcos", "Sacco di farina", "Ciotola di legno", "Marco Mengoni", 
    "Isola di Sant'Antioco", "Prabowo Subianto", "Un sospiro imbottigliato", "La dentiera di un vampiro vegetariano", "Una nuvola da passeggio", "Il numero di telefono di Atlantide", 
    "Un calzino che ha perso il suo compagno nel 1994", "L'ombra di una forchetta", "Un manuale d'istruzioni per sognare", 
    "Una foto polaroid di un fantasma timido", "Il riflesso di uno specchio rotto", "Un cubetto di ghiaccio che non si scioglie mai", 
    "La pazienza di un santo (confezione da 50ml)", "Un sasso che crede di essere un uovo", "Il segreto meglio custodito di un gatto", 
    "Una chiave che apre solo le porte girevoli", "Un raggio di luna conservato sotto sale", "L'ego di un influencer in miniatura", 
    "Una bussola che punta sempre verso il frigo", "Un libro scritto interamente in codice fiscale", 
    "La ricevuta di un acquisto fatto in un sogno", "Un bullone proveniente da un UFO di seconda mano", "Una boccetta di nebbia milanese", 
    "Il primo pensiero del mattino di un bradipo", "Una moneta da tre euro", "Un petalo di margherita metallico", 
    "La colla per riparare i cuori infranti", "Un telecomando per cambiare il meteo", "Una piuma di piccione placcata oro", 
    "Il ronzio di una zanzara intrappolato in un barattolo", "Un foglio di carta trasparente", "Una candela che profuma di pioggia imminente", 
    "L'impronta digitale di un alieno", "Un cronometro che segna solo i momenti felici", 
    "Una mappa per trovare le chiavi perdute", "Un seme di pianta invisibile", "Il tasto 'Esc' di una macchina da scrivere", 
    "Una fiala di acqua piovana del Giurassico", "Un dado a una sola faccia", "La polvere magica trovata sotto il divano", 
    "Un fischietto per richiamare i sogni lucidi", "Una scaglia di pelle di dinosauro sintetico", "Un pennello per dipingere sull'acqua", 
    "L'eco di un urlo nello spazio", "Un frammento di unghia di gigante", "Una bolla di sapone che non scoppia", "Un pettine per calvi", 
    "Il biglietto da visita di un viaggiatore del tempo", "Una lampadina che emette oscurità", "Un cucchiaio piegato con la forza del pensiero", 
    "L'indirizzo preciso dell'Isola che non c'è", "Una palla di lana raccolta da un buco nero"

]

random.shuffle(_items)

def get_item():
    return random.choice(_items)

def randomitem():
    return get_item()
